-- =========================================================
-- Snowflake setup for Synapse backend running on AWS
-- Execute with ACCOUNTADMIN (or equivalent admin role)
-- =========================================================

USE ROLE ACCOUNTADMIN;

-- -----------------------------
-- 0) Replace placeholders first
-- -----------------------------
SET APP_USER   = 'SYNAPSE_SERVICE_USER';
SET APP_ROLE   = 'SYNAPSE_APP_ROLE';
SET APP_WH     = 'COMPUTE_WH';
SET RAG_DB     = 'DB_BT_UA';
SET RAG_SCHEMA = 'BT_UA_MART_ANALYTICS';
SET ADS_DB     = 'UA_ECOMM';
SET ADS_SCHEMA = 'PUBLIC';
SET POLICY_NAME = 'SYNAPSE_AWS_EGRESS_POLICY';

-- Use the Elastic IP assigned to your NAT Gateway (egress)
-- Add all egress IPs if you use multiple NAT Gateways.
-- Example:
-- CREATE NETWORK POLICY IDENTIFIER($POLICY_NAME)
--   ALLOWED_IP_LIST = ('203.0.113.10/32', '203.0.113.11/32')
--   COMMENT = 'Allow AWS egress for Synapse backend';

-- -----------------------------
-- 1) Create app role
-- -----------------------------
CREATE ROLE IF NOT EXISTS IDENTIFIER($APP_ROLE);

-- -----------------------------
-- 2) Grant minimum privileges
-- -----------------------------
GRANT USAGE ON WAREHOUSE IDENTIFIER($APP_WH) TO ROLE IDENTIFIER($APP_ROLE);
GRANT OPERATE ON WAREHOUSE IDENTIFIER($APP_WH) TO ROLE IDENTIFIER($APP_ROLE);

GRANT USAGE ON DATABASE IDENTIFIER($RAG_DB) TO ROLE IDENTIFIER($APP_ROLE);
GRANT USAGE ON SCHEMA IDENTIFIER($RAG_DB || '.' || $RAG_SCHEMA) TO ROLE IDENTIFIER($APP_ROLE);
GRANT SELECT ON ALL TABLES IN SCHEMA IDENTIFIER($RAG_DB || '.' || $RAG_SCHEMA) TO ROLE IDENTIFIER($APP_ROLE);
GRANT SELECT ON FUTURE TABLES IN SCHEMA IDENTIFIER($RAG_DB || '.' || $RAG_SCHEMA) TO ROLE IDENTIFIER($APP_ROLE);
GRANT SELECT ON ALL VIEWS IN SCHEMA IDENTIFIER($RAG_DB || '.' || $RAG_SCHEMA) TO ROLE IDENTIFIER($APP_ROLE);
GRANT SELECT ON FUTURE VIEWS IN SCHEMA IDENTIFIER($RAG_DB || '.' || $RAG_SCHEMA) TO ROLE IDENTIFIER($APP_ROLE);

GRANT USAGE ON DATABASE IDENTIFIER($ADS_DB) TO ROLE IDENTIFIER($APP_ROLE);
GRANT USAGE ON SCHEMA IDENTIFIER($ADS_DB || '.' || $ADS_SCHEMA) TO ROLE IDENTIFIER($APP_ROLE);
GRANT SELECT ON ALL TABLES IN SCHEMA IDENTIFIER($ADS_DB || '.' || $ADS_SCHEMA) TO ROLE IDENTIFIER($APP_ROLE);
GRANT SELECT ON FUTURE TABLES IN SCHEMA IDENTIFIER($ADS_DB || '.' || $ADS_SCHEMA) TO ROLE IDENTIFIER($APP_ROLE);
GRANT SELECT ON ALL VIEWS IN SCHEMA IDENTIFIER($ADS_DB || '.' || $ADS_SCHEMA) TO ROLE IDENTIFIER($APP_ROLE);
GRANT SELECT ON FUTURE VIEWS IN SCHEMA IDENTIFIER($ADS_DB || '.' || $ADS_SCHEMA) TO ROLE IDENTIFIER($APP_ROLE);

-- -----------------------------
-- 3) Attach role to service user
-- -----------------------------
GRANT ROLE IDENTIFIER($APP_ROLE) TO USER IDENTIFIER($APP_USER);
ALTER USER IDENTIFIER($APP_USER) SET DEFAULT_ROLE = IDENTIFIER($APP_ROLE);
ALTER USER IDENTIFIER($APP_USER) SET DEFAULT_WAREHOUSE = IDENTIFIER($APP_WH);

-- -----------------------------
-- 4) Apply network policy
-- -----------------------------
-- Create/update the policy with your AWS NAT Elastic IP(s), then apply:
-- ALTER USER IDENTIFIER($APP_USER) SET NETWORK_POLICY = IDENTIFIER($POLICY_NAME);

-- -----------------------------
-- 5) Diagnostics
-- -----------------------------
SHOW NETWORK POLICIES;
SHOW PARAMETERS LIKE 'NETWORK_POLICY' IN ACCOUNT;
SHOW PARAMETERS LIKE 'NETWORK_POLICY' IN USER IDENTIFIER($APP_USER);
SHOW GRANTS TO ROLE IDENTIFIER($APP_ROLE);
SHOW GRANTS TO USER IDENTIFIER($APP_USER);

-- -----------------------------
-- 6) Functional checks
-- -----------------------------
USE ROLE IDENTIFIER($APP_ROLE);
USE WAREHOUSE IDENTIFIER($APP_WH);
USE DATABASE IDENTIFIER($RAG_DB);
USE SCHEMA IDENTIFIER($RAG_SCHEMA);

SELECT CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE(), CURRENT_DATABASE(), CURRENT_SCHEMA();
SELECT COUNT(*) AS CNT_FORMULAS FROM IDENTIFIER($RAG_DB || '.' || $RAG_SCHEMA || '.FORMULAS_MARKETING');

-- Adjust table name if needed
SELECT COUNT(*) AS CNT_ADS FROM IDENTIFIER($ADS_DB || '.' || $ADS_SCHEMA || '.GOOGLE_ADS_METRICAS');

-- Cortex check
SELECT SNOWFLAKE.CORTEX.COMPLETE('mistral-large2', $$Respond only: OK$$) AS CORTEX_OK;
